-- CREATE DATABASE IF NOT EXISTS batch;

DROP TABLE IF EXISTS `order`;
CREATE TABLE IF NOT EXISTS `order` (
  `CUST_ID` varchar(255) NOT NULL,
  `ORDERNUM` varchar(255) NOT NULL,
  `COUNTRY` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`CUST_ID`)

);
